A few changes/suggestions:
limengbinggz/ddtlcm pull request #13
Opened 2024-02-26 23:13 UTC by jamesuanhoro

- If number of iterations exceeds 10, update user at every 10% -- implementation is not elegant
- Show percentages in treemap
- "rea-valued" => "real-valued" in documentation

2024-03-14 22:54 UTC, limengbinggz approved these changes

2024-03-14 22:59 UTC, limengbinggz requested changes
Thank you for the suggestions. I am certain that all changes, possibly except for the changes to R/plot_functions.R, improve the quality of the package. I am reluctant to merge the changes to R/plot_functions.R because I think showing the class probabilities as numbers between 0 and 1 would not create any confusion about the numbers, and would also emphasize the fact that these numbers are indeed probabilities and add up to 1. Would you reconsider making these changes? Thank you.

2024-03-25 03:52 UTC, limengbinggz approved these changes

2024-03-25 03:54 UTC, merged

2024-03-25 23:10 UTC, jamesuanhoro commented
> Thank you for the suggestions. I am certain that all changes, possibly except for the changes to R/plot_functions.R, improve the quality of the package. I am reluctant to merge the changes to R/plot_functions.R because I think showing the class probabilities as numbers between 0 and 1 would not create any confusion about the numbers, and would also emphasize the fact that these numbers are indeed probabilities and add up to 1. Would you reconsider making these changes? Thank you.

Sorry I'm just seeing this. Of course however you decide to handle these are fine -- they're cosmetic.

2024-03-26 19:03 UTC, limengbinggz commented
> > Thank you for the suggestions. I am certain that all changes, possibly except for the changes to R/plot_functions.R, improve the quality of the package. I am reluctant to merge the changes to R/plot_functions.R because I think showing the class probabilities as numbers between 0 and 1 would not create any confusion about the numbers, and would also emphasize the fact that these numbers are indeed probabilities and add up to 1. Would you reconsider making these changes? Thank you.
> 
> Sorry I'm just seeing this. Of course however you decide to handle these are fine -- they're cosmetic. Since you merged it already, I hope you updated it how best you saw fit(?)

Thank you for your understanding. But I agree with you that this cosmetic changes shall not be concerning, so I have merged your changes into the code. Thank you again for the suggestions!